language: node_js

node_js:
  - lts/*

os: linux

dist: focal

branches:
  only:
    - master
    - /^v[0-9]+.*$/

cache: yarn

install:
  - yarn install

script:
  - npm run build:prod


jobs:
  include:
    - stage: Build
      script: yarn run build:prod
    - stage: npm release
      script: yarn run build:prod
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_token: "$NPM_API_TOKEN"
        cleanup: true
        on:
          tags: true
